In [1]:
import numpy as np

In [2]:
a= np.array([2,3,4])

In [3]:
a

array([2, 3, 4])

In [5]:
a.dtype

dtype('int64')

In [6]:
a= np.array([(1,3),(2,4),(5,6)])
a

array([[1, 3],
       [2, 4],
       [5, 6]])

In [7]:
a[0,:]


array([1, 3])

In [9]:
a[0,1]


3

In [10]:
a[0:2,1]


array([3, 4])

In [15]:
a[0:2,1]


array([3, 4])

In [16]:
a[0:2,0:2]


array([[1, 3],
       [2, 4]])

In [17]:
a[0:3,0:3]


array([[1, 3],
       [2, 4],
       [5, 6]])

In [19]:
a[1:3,1:3]


array([[4],
       [6]])

In [21]:
a.ndim

2

In [22]:
a.shape

(3, 2)

In [23]:
np.reshape(a,(2,3))


array([[1, 3, 2],
       [4, 5, 6]])

In [25]:
np.reshape(a,(1,-1))


array([[1, 3, 2, 4, 5, 6]])

In [26]:
np.reshape(a,(-1,1))


array([[1],
       [3],
       [2],
       [4],
       [5],
       [6]])

In [27]:
a<4


array([[ True,  True],
       [ True, False],
       [False, False]])

In [29]:
x= np.array([(1,2),(3,4)])
x

array([[1, 2],
       [3, 4]])

In [30]:
y= np.array([(2,1),(4,3)])
y

array([[2, 1],
       [4, 3]])

In [31]:
x*y

array([[ 2,  2],
       [12, 12]])

In [32]:
x.dot(y)

array([[10,  7],
       [22, 15]])

In [33]:
#arange

In [36]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(1,10,step=3)


array([1, 4, 7])

In [38]:
np.arange(10,step2)


NameError: name 'step2' is not defined

In [39]:
np.arange(6).reshape(2,3)


array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
np.linspace(1,8,num=3)


array([1. , 4.5, 8. ])

In [48]:
np.linspace(0,2,5)



array([0. , 0.5, 1. , 1.5, 2. ])

In [49]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [50]:
np.ones(6)


array([1., 1., 1., 1., 1., 1.])

In [51]:
np.empty(3)


array([1. , 4.5, 8. ])

In [55]:
np.empty(4)


array([0.5, 1. , 1.5, 2. ])

In [56]:
np.full((2,2),4)


array([[4, 4],
       [4, 4]])

In [59]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
t= np.arange(3)
t

array([0, 1, 2])

In [62]:
np.sqrt(t)

array([0.        , 1.        , 1.41421356])

In [63]:
np.exp(t)


array([1.        , 2.71828183, 7.3890561 ])

In [64]:
p=np.array([(1,5,3),(8,2,6)])
p

array([[1, 5, 3],
       [8, 2, 6]])

In [65]:
p.sum(axis=0)


array([9, 7, 9])

In [66]:
p.sum(axis=1)


array([ 9, 16])

In [67]:
p.min(axis=0)


array([1, 2, 3])

In [68]:
p.min(axis=1)


array([1, 2])

In [70]:
np.sort(p,axis=None)


array([1, 2, 3, 5, 6, 8])

In [71]:
np.sort(p)


array([[1, 3, 5],
       [2, 6, 8]])

In [84]:
np.random.seed(1)
np.random.randint(10)


5

In [85]:
np.random.rand(2)


array([0.99718481, 0.93255736])

In [89]:
np.random.uniform(5,size=(3,3))


array([[1.61475633, 3.74690593, 2.90180736],
       [3.22618842, 4.08169115, 2.86234436],
       [1.3441519 , 3.17118077, 3.27720573]])

In [90]:
np.random.randn(5)


array([ 0.8858294 ,  0.63190187,  0.04026035, -0.90312288,  0.17532267])